INSERT INTO form
	(nome, cognome, email, messaggio)
VALUES
	('Giorgio', 'Gialli', 'giorgio.gialli1@example.com', 'Vi seguo sempre con interesse ❤️'),
	('Fatima', 'Viola', 'fatima.viola2@example.com', '素晴らしいですね！✨'),
	('Elena', 'Zhang', 'elena.zhang3@example.com', 'Nice interface! 🖥️'),
	('Zara', 'Neri', 'zara.neri4@example.com', 'Sehr schön! 🌈'),
	('Marco', 'Gialli', 'marco.gialli5@example.com', 'Vi seguo sempre con interesse ❤️'),
	('Giorgio', 'Viola', 'giorgio.viola6@example.com', 'Bellissima grafica 🎨'),
	('Hans', 'Hussein', 'hans.hussein7@example.com', 'Хорошая работа! 💼'),
	('Hans', 'Argento', 'hans.argento8@example.com', '¡Buen trabajo! 💪'),
	('Chiara', 'Garcia', 'chiara.garcia9@example.com', 'Je vous adore! 😘'),
	('Giorgio', 'Verdi', 'giorgio.verdi10@example.com', 'Davvero utile! 🙌'),
	('Luisa', 'Nguyen', 'luisa.nguyen11@example.com', 'Grazie mille! 🙏'),
	('Luisa', 'Viola', 'luisa.viola12@example.com', 'Ottimo lavoro! 🔥'),
	('Wei', 'Zhang', 'wei.zhang13@example.com', 'Bellissima grafica 🎨'),
	('Franco', 'Viola', 'franco.viola14@example.com', 'Nice interface! 🖥️'),
	('Fatima', 'Garcia', 'fatima.garcia15@example.com', 'Ottimo lavoro! 🔥'),
	('Luca', 'Yamamoto', 'luca.yamamoto16@example.com', 'Sehr schön! 🌈'),
	('Luisa', 'Neri', 'luisa.neri17@example.com', 'Great job! 👏'),
	('Wei', 'Bianchi', 'wei.bianchi18@example.com', 'Fantastico! 😍'),
	('Emily', 'Kumar', 'emily.kumar19@example.com', 'Complimenti per il sito! 👍'),
	('Elena', 'Zhang', 'elena.zhang20@example.com', 'Ciao a tutti! 😀'),
	('Chiara', 'Blu', 'chiara.blu21@example.com', 'Complimenti per il sito! 👍'),
	('Hans', 'Rame', 'hans.rame22@example.com', 'Fantastico! 😍'),
	('Emily', 'Argento', 'emily.argento23@example.com', '¡Buen trabajo! 💪'),
	('John', 'Argento', 'john.argento24@example.com', '你好，做得好！🌟'),
	('Ivan', 'Rossi', 'ivan.rossi25@example.com', 'Vi seguo sempre con interesse ❤️'),
	('Marco', 'Bianchi', 'marco.bianchi26@example.com', 'Je vous adore! 😘'),
	('Elena', 'Yamamoto', 'elena.yamamoto27@example.com', 'Nice interface! 🖥️'),
	('Giorgio', 'Nguyen', 'giorgio.nguyen28@example.com', 'Ciao a tutti! 😀'),
	('Elena', 'Silva', 'elena.silva29@example.com', 'Vi seguo sempre con interesse ❤️'),
	('Giorgio', 'Viola', 'giorgio.viola30@example.com', 'Mi avete fatto sorridere 😄'),
	('Luisa', 'Ivanov', 'luisa.ivanov31@example.com', 'Mi avete fatto sorridere 😄'),
	('Hans', 'Ivanov', 'hans.ivanov32@example.com', 'Vi seguo sempre con interesse ❤️'),
	('Giorgio', 'Neri', 'giorgio.neri33@example.com', 'Vi seguo sempre con interesse ❤️'),
	('Anna', 'Argento', 'anna.argento34@example.com', 'Grazie mille! 🙏'),
	('Hans', 'Blu', 'hans.blu35@example.com', 'Un saluto da Roma! 🏛️'),
	('Wei', 'Verdi', 'wei.verdi36@example.com', 'Nice interface! 🖥️'),
	('Aiko', 'Rame', 'aiko.rame37@example.com', 'Mi avete fatto sorridere 😄'),
	('Mario', 'Hussein', 'mario.hussein38@example.com', '素晴らしいですね！✨'),
	('Carlos', 'Blu', 'carlos.blu39@example.com', 'Bellissima grafica 🎨'),
	('Wei', 'Bianchi', 'wei.bianchi40@example.com', '¡Buen trabajo! 💪'),
	('Elena', 'Neri', 'elena.neri41@example.com', 'Complimenti per il sito! 👍'),
	('Chiara', 'Neri', 'chiara.neri42@example.com', 'Great job! 👏'),
	('Carlos', 'Hussein', 'carlos.hussein43@example.com', 'Fantastico! 😍'),
	('Hans', 'Gialli', 'hans.gialli44@example.com', 'Ciao a tutti! 😀'),
	('Aiko', 'Gialli', 'aiko.gialli45@example.com', 'Je vous adore! 😘'),
	('Luisa', 'Argento', 'luisa.argento46@example.com', 'Complimenti per il sito! 👍'),
	('Sofia', 'Rossi', 'sofia.rossi47@example.com', 'Un saluto da Roma! 🏛️'),
	('Giulia', 'Rossi', 'giulia.rossi48@example.com', 'Je vous adore! 😘'),
	('Luca', 'Smith', 'luca.smith49@example.com', 'Grazie mille! 🙏'),
	('Anna', 'Yamamoto', 'anna.yamamoto50@example.com', 'Fantastico! 😍'),
	('Mario', 'Bianchi', 'mario.bianchi51@example.com', 'Nice interface! 🖥️'),
	('Carlos', 'Kumar', 'carlos.kumar52@example.com', 'Grazie mille! 🙏'),
	('Emily', 'Garcia', 'emily.garcia53@example.com', 'Excelente presentación! 🧡'),
	('Mario', 'Blu', 'mario.blu54@example.com', 'Bellissima grafica 🎨'),
	('Anna', 'Rame', 'anna.rame55@example.com', '¡Buen trabajo! 💪'),
	('Giorgio', 'Viola', 'giorgio.viola56@example.com', 'Sehr schön! 🌈'),
	('Elena', 'Yamamoto', 'elena.yamamoto57@example.com', 'Ottimo lavoro! 🔥'),
	('Aiko', 'Smith', 'aiko.smith58@example.com', 'Che bella iniziativa 😊'),
	('Anna', 'Silva', 'anna.silva59@example.com', 'Bellissima grafica 🎨'),
	('Wei', 'Verdi', 'wei.verdi60@example.com', 'Grazie mille! 🙏'),
	('Hans', 'Rame', 'hans.rame61@example.com', 'Je vous adore! 😘'),
	('Aiko', 'Neri', 'aiko.neri62@example.com', 'Хорошая работа! 💼'),
	('Marco', 'Müller', 'marco.müller63@example.com', 'Vi seguo sempre con interesse ❤️'),
	('Hans', 'Viola', 'hans.viola64@example.com', 'Хорошая работа! 💼'),
	('Giulia', 'Smith', 'giulia.smith65@example.com', 'Excelente presentación! 🧡'),
	('John', 'Blu', 'john.blu66@example.com', 'Che bella iniziativa 😊'),
	('Carlos', 'Verdi', 'carlos.verdi67@example.com', 'Ottimo lavoro! 🔥'),
	('Elena', 'Blu', 'elena.blu68@example.com', 'Хорошая работа! 💼'),
	('Fatima', 'Rame', 'fatima.rame69@example.com', 'Je vous adore! 😘'),
	('Luca', 'Yamamoto', 'luca.yamamoto70@example.com', 'Mi avete fatto sorridere 😄'),
	('Sofia', 'Kumar', 'sofia.kumar71@example.com', 'Great job! 👏'),
	('Elena', 'Neri', 'elena.neri72@example.com', 'Ciao a tutti! 😀'),
	('Marco', 'Müller', 'marco.müller73@example.com', 'Che bella iniziativa 😊'),
	('Zara', 'Argento', 'zara.argento74@example.com', 'Bellissima grafica 🎨'),
	('Franco', 'Bronzo', 'franco.bronzo75@example.com', 'Sehr schön! 🌈'),
	('John', 'Bianchi', 'john.bianchi76@example.com', 'Vi seguo sempre con interesse ❤️'),
	('Giulia', 'Smith', 'giulia.smith77@example.com', 'Bellissima grafica 🎨'),
	('Hans', 'Ivanov', 'hans.ivanov78@example.com', 'Sehr schön! 🌈'),
	('Ivan', 'Nguyen', 'ivan.nguyen79@example.com', '你好，做得好！🌟'),
	('Giulia', 'Hussein', 'giulia.hussein80@example.com', 'Complimenti per il sito! 👍'),
	('Fatima', 'Silva', 'fatima.silva81@example.com', 'Vi seguo sempre con interesse ❤️'),
	('Chiara', 'Gialli', 'chiara.gialli82@example.com', 'Nice interface! 🖥️'),
	('Giulia', 'Yamamoto', 'giulia.yamamoto83@example.com', 'Che bella iniziativa 😊'),
	('Sofia', 'Rossi', 'sofia.rossi84@example.com', '你好，做得好！🌟'),
	('Sofia', 'Viola', 'sofia.viola85@example.com', '¡Buen trabajo! 💪'),
	('Luca', 'Verdi', 'luca.verdi86@example.com', 'Je vous adore! 😘'),
	('Emily', 'Bronzo', 'emily.bronzo87@example.com', 'Complimenti per il sito! 👍'),
	('Mario', 'Nguyen', 'mario.nguyen88@example.com', 'Ottimo lavoro! 🔥'),
	('Fatima', 'Rame', 'fatima.rame89@example.com', 'Bellissima grafica 🎨'),
	('Zara', 'Nguyen', 'zara.nguyen90@example.com', 'Хорошая работа! 💼'),
	('Zara', 'Verdi', 'zara.verdi91@example.com', 'Ciao a tutti! 😀'),
	('Mario', 'Müller', 'mario.müller92@example.com', 'Grazie mille! 🙏'),
	('Sofia', 'Argento', 'sofia.argento93@example.com', 'Un saluto da Roma! 🏛️'),
	('Emily', 'Smith', 'emily.smith94@example.com', 'Complimenti per il sito! 👍'),
	('John', 'Smith', 'john.smith95@example.com', 'Ciao a tutti! 😀'),
	('Luisa', 'Zhang', 'luisa.zhang96@example.com', 'Ciao a tutti! 😀'),
	('Giorgio', 'Kumar', 'giorgio.kumar97@example.com', '你好，做得好！🌟'),
	('Luca', 'Blu', 'luca.blu98@example.com', 'Davvero utile! 🙌'),
	('Wei', 'Ivanov', 'wei.ivanov99@example.com', 'Sehr schön! 🌈'),
	('Hans', 'Verdi', 'hans.verdi100@example.com', 'Excelente presentación! 🧡');
